name: Build GitHub Pages

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - name: Checkout master branch
              uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: yarn --frozen-lockfile

            - name: Build website
              run: yarn build

            - name: Copy build to docs
              run: cp -a build docs

            - name: Push changes to github-pages branch
              run: |
                  git config --global user.email 'GitHub Actions'
                  git config --global user.name 'github-actions@github.com'
                  git checkout -b github-pages
                  git add --all
                  git commit --message='auto-updated github-pages'
                  git push --force --set-upstream origin github-pages
