name: Push from master branch to github-pages branch

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout master branch
              uses: actions/checkout@v2

            - name: Push from master branch to github-pages branch
              run: |
                  git config --global user.email "GitHub Actions"
                  git config --global user.name "github-actions@github.com"
                  git checkout -b github-pages
                  git push --force --set-upstream origin github-pages
