name: Push from master branch to github-pages branch

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - name: Checkout master branch
              uses: actions/checkout@v2

            - name: Push from master branch to github-pages branch
              run: |
                  git checkout -b github-pages
                  git merge master
                  git push --force --set-upstream origin github-pages
