name: Push from master branch to github-pages branch

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        # strategy:
        #     matrix:
        #         node-version: [12.x]

        steps:
            - name: Checkout master branch
              uses: actions/checkout@v2

            - name: Push from master branch to github-pages branch
              run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git checkout -b github-pages
                  git push --force --set-upstream origin github-pages
